name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, lts/*]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ matrix.node }}-
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Source production environment file
        run: source .env.production
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Check for vulnerabilities
        run: npm audit --production
      - name: Build production artifact
        run: npm run build
      - name: Test production build
        run: npm run test:prod
      # - name: Run tests with coverage
      #   run: npm run test:coverage
