name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, lts/*]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ matrix.node }}-
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Check for vulnerabilities
        run: npm audit --production
      - name: Run tests
        run: npm test
      - name: Run tests with coverage (optional)
        run: npm run test:coverage
      - name: Build production artifact
        run: npm run build
      - name: Install production dependencies
        run: npm ci --omit=dev
      - name: Prune development dependencies and check for missing dependencies
        run: |
          npm prune --omit=dev
          if [ -f package-lock.json ] && [ -n "$(npm ls --production --parseable | grep -v "$(pwd)")" ]; then
            echo 'Some production dependencies are missing, check the "npm ls" output above'
            exit 1
          fi
